apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: annasmelova/online_inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 5
      livenessProbe:
            httpGet:
                path: /health
                port: 8000            
            initialDelaySeconds: 40
            periodSeconds: 10